# Generated by Django 5.1.4 on 2025-02-05 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motorista', '0002_alter_motorista_cnpj_alter_motorista_cpf'),
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa', models.CharField(max_length=30)),
                ('data_pagamento', models.DateField()),
                ('km_atual', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('valor_semanal', models.CharField(blank=True, max_length=30)),
                ('dia_debito', models.CharField(blank=True, max_length=30)),
                ('valor_pago', models.CharField(blank=True, max_length=30)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorista.motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculo.veiculo')),
            ],
        ),
    ]
